#!/bin/bash

# Script to restore moved files
# Generated on Wed Mar 26 11:41:25 CDT 2025

mkdir -p src
mv src/_unused/vue/App.vue src/App.vue
mkdir -p src
mv src/_unused/vue/AppWithRouter.vue src/AppWithRouter.vue
mkdir -p src/components
mv src/_unused/vue/ThemeSwitcher.vue src/components/ThemeSwitcher.vue
mkdir -p src/components/ui
mv src/_unused/vue/GradientDefinitions.vue src/components/ui/GradientDefinitions.vue
mkdir -p src/components/ui
mv src/_unused/vue/ScrollAccordionVanilla.vue src/components/ui/ScrollAccordionVanilla.vue
mkdir -p src/components/ui/backgrounds
mv src/_unused/vue/GridPaperOverlay.vue src/components/ui/backgrounds/GridPaperOverlay.vue
mkdir -p src/components/ui/containers
mv src/_unused/vue/ScrollPinWrapper.vue src/components/ui/containers/ScrollPinWrapper.vue
mkdir -p src/components/ui
mv src/_unused/vue/AvailabilityBadge.vue src/components/ui/AvailabilityBadge.vue
mkdir -p src/components
mv src/_unused/vue/PhoneSection2.vue src/components/PhoneSection2.vue
mkdir -p src/components/sections
mv src/_unused/vue/ContactSectionV2.vue src/components/sections/ContactSectionV2.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/PlainMessageLayout.vue src/components/sections/refactored/PlainMessageLayout.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/HeroSectionNoPhone.vue src/components/sections/refactored/HeroSectionNoPhone.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/PhoneContentLayout.vue src/components/sections/refactored/PhoneContentLayout.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/ScrollablePhoneSection.vue src/components/sections/refactored/ScrollablePhoneSection.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/Timeline.vue src/components/sections/refactored/Timeline.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/AmbientScreen.vue src/components/sections/refactored/AmbientScreen.vue
mkdir -p src/components/sections/refactored
mv src/_unused/vue/HeroSection.vue src/components/sections/refactored/HeroSection.vue
mkdir -p src/components/sections
mv src/_unused/vue/AboutSectionAlt.vue src/components/sections/AboutSectionAlt.vue
mkdir -p src/components/sections
mv src/_unused/vue/WebsiteSolutionsHeader.vue src/components/sections/WebsiteSolutionsHeader.vue
mkdir -p src/components/sections
mv src/_unused/vue/ScrollableCardsSection.vue src/components/sections/ScrollableCardsSection.vue
mkdir -p src/components/sections
mv src/_unused/vue/StrugglesOffersTabs.vue src/components/sections/StrugglesOffersTabs.vue
mkdir -p src/components
mv src/_unused/vue/LoadingDots.vue src/components/LoadingDots.vue
mkdir -p src/components
mv src/_unused/vue/PhoneSection.vue src/components/PhoneSection.vue
mkdir -p src/components/layout
mv src/_unused/vue/Navbar.vue src/components/layout/Navbar.vue
mkdir -p src/components/layout
mv src/_unused/vue/Footer.vue src/components/layout/Footer.vue
mkdir -p src/components/layout
mv src/_unused/vue/ContactForm.vue src/components/layout/ContactForm.vue
mkdir -p src/components/export-to-main/card3D
mv src/_unused/vue/Card3DShowcase.vue src/components/export-to-main/card3D/Card3DShowcase.vue
mkdir -p src/components/export-to-main/card3D
mv src/_unused/vue/Card3D.vue src/components/export-to-main/card3D/Card3D.vue
mkdir -p src/components/export-to-main/animatedText
mv src/_unused/vue/usage-example.vue src/components/export-to-main/animatedText/usage-example.vue
mkdir -p src/components/export-to-main/animatedText
mv src/_unused/vue/delay-test.vue src/components/export-to-main/animatedText/delay-test.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections/refactored
mv src/_unused/vue/HeroSectionChat.vue src/components/export-to-main/home-rebuilt/src/components/sections/refactored/HeroSectionChat.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections/refactored
mv src/_unused/vue/ScrollableChatSectionV2.vue src/components/export-to-main/home-rebuilt/src/components/sections/refactored/ScrollableChatSectionV2.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections/refactored
mv src/_unused/vue/HurdlesSolutionsSection.vue src/components/export-to-main/home-rebuilt/src/components/sections/refactored/HurdlesSolutionsSection.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections/refactored
mv src/_unused/vue/ServicesSection.vue src/components/export-to-main/home-rebuilt/src/components/sections/refactored/ServicesSection.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections/refactored
mv src/_unused/vue/StickyScrollableCardsSection.vue src/components/export-to-main/home-rebuilt/src/components/sections/refactored/StickyScrollableCardsSection.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections/refactored
mv src/_unused/vue/ScrollableChatSection.vue src/components/export-to-main/home-rebuilt/src/components/sections/refactored/ScrollableChatSection.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/sections
mv src/_unused/vue/TimelineHowItWorks.vue src/components/export-to-main/home-rebuilt/src/components/sections/TimelineHowItWorks.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/scroll
mv src/_unused/vue/ScrollPinWrapper.vue src/components/export-to-main/home-rebuilt/src/components/scroll/ScrollPinWrapper.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components
mv src/_unused/vue/GridPaperOverlay.vue src/components/export-to-main/home-rebuilt/src/components/GridPaperOverlay.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components
mv src/_unused/vue/TypingIndicator.vue src/components/export-to-main/home-rebuilt/src/components/TypingIndicator.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components
mv src/_unused/vue/FloatingChatInterface.vue src/components/export-to-main/home-rebuilt/src/components/FloatingChatInterface.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components/effects
mv src/_unused/vue/EmberEffect.vue src/components/export-to-main/home-rebuilt/src/components/effects/EmberEffect.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/components
mv src/_unused/vue/LazySection.vue src/components/export-to-main/home-rebuilt/src/components/LazySection.vue
mkdir -p src/components/export-to-main/home-rebuilt/src/views
mv src/_unused/vue/HomeRebuilt.vue src/components/export-to-main/home-rebuilt/src/views/HomeRebuilt.vue
mkdir -p src/components/export-to-main/gridBackground
mv src/_unused/vue/usage-example.vue src/components/export-to-main/gridBackground/usage-example.vue
mkdir -p src/components/export-to-main/scrollAccordion
mv src/_unused/vue/usage-example.vue src/components/export-to-main/scrollAccordion/usage-example.vue
mkdir -p src/components
mv src/_unused/vue/ChatScreen.vue src/components/ChatScreen.vue
mkdir -p src/components
mv src/_unused/vue/PhoneMessages2.vue src/components/PhoneMessages2.vue
mkdir -p src/components
mv src/_unused/vue/FloatingPhone.vue src/components/FloatingPhone.vue
mkdir -p src/components
mv src/_unused/vue/PhoneMessages.vue src/components/PhoneMessages.vue
mkdir -p src/components/text
mv src/_unused/vue/AnimatedText.vue src/components/text/AnimatedText.vue
mkdir -p src/components
mv src/_unused/vue/ServicesAccordion.vue src/components/ServicesAccordion.vue
mkdir -p src/views
mv src/_unused/vue/Home.vue src/views/Home.vue
mkdir -p src/views
mv src/_unused/vue/FloatingChatDemo.vue src/views/FloatingChatDemo.vue
mkdir -p src/views
mv src/_unused/vue/Playground.vue src/views/Playground.vue
mkdir -p src/views
mv src/_unused/vue/ChatSectionsDemo.vue src/views/ChatSectionsDemo.vue
mkdir -p src/utils
mv src/_unused/js/titleCardEdgeDetection.js src/utils/titleCardEdgeDetection.js
mkdir -p src/components/effects
mv src/_unused/js/particleEffects.js src/components/effects/particleEffects.js
